# 暴露端口
server:
  port: 8888
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ai-thesis.cc:3306/init?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
#  Redis 默认禁用
#  redis:
#    # redis数据库索引(默认为0)，我们使用索引为3的数据库，避免和其他数据库冲突
#    database: 0
#    # redis服务器地址（默认为localhost）
#    host: ai-thesis.cc
#    # redis端口（默认为6379）
#    port: 6379
#    # redis访问密码（默认为空）
#    password: admin123
#    # redis连接超时时间（单位毫秒）
#    timeout: 0
#    # redis连接池配置
#    pool:
#      # 最大可用连接数（默认为8，负数表示无限）
#      max-active: 8
#      # 最大空闲连接数（默认为8，负数表示无限）
#      max-idle: 8
#      # 最小空闲连接数（默认为0，该值只有为正数才有用）
#      min-idle: 0
#      # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
#      max-wait: -1

