spring:
  config:
    activate:
      on-profile: dev
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/init?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

# 微信
we-chat:
  # APPID
  appId: 'xxxxxxxxxx'
  # 密钥
  secret: 'xxxxxxxxxx'
  # 通知模板
  template: '微信通知模板'

# 百度翻译
baidu-translation:
  # 百度翻译Appid
  appid: ''
  # 百度翻译密码要
  secret: ''
# 阿里云短信
aliyun:
  product: 'Dysmsapi'
  domain: 'dysmsapi.aliyuncs.com'
  accessKey: 'AccessKeyId'
  accessSecret: 'AccesskeySecret'

file:
  path: C://upload/
